package com.anothercaffeinatedday.ws.soap.utclient;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * The Default entry point.
 *
 * <p>Generated by the Spring Initializr.</p>
 */
@SpringBootApplication
public class UtclientApplication {

  public static void main(String[] args) {
    SpringApplication.run(UtclientApplication.class, args);
  }

}
